server:
  error:
    include-message: always
    include-binding-errors: always
api :
  isSandBoxMode : true

logging:
  file:
    name: logs/TinkoffService.log
  level:
    root: INFO
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/register
    username: postgres
    password: 3290
    driverClassName: org.postgresql.Driver

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000